steps:
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=ap-south-1b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ecs-stack-1-ECSCluster-E0VZ40825K6F'
